### ISSUE TITLE
Subscriptions cannot be restricted to Sysadmin Role

### ISSUE THREAD

**Issue by DHaussermann** [mattermost/mattermost-plugin-confluence#30]
There is no way to limit access to create subscriptions to the sysadmin role. This should be implemented.
Since there is no user mapping and permission checking on the Atlasian side, we should at least have the ability to restrict the functionality on the Mattermost side.

**Comment by jprusch** [comment]
This should be configurable per team. We have channels, where the user should be able to manage this for himself, other teams will need at least team admin oder sysadmin role to manage this.

**Comment by aaronrothschild** [comment]
We should allow Sysadmins to change subscriptions on all channels.

There should be an option allowing an admin to specify "Channel Admins can create subscriptions in channels they manage without an admin level of access" on the system console for the plugin.  This would let channel admins control subscriptions themselves. 

In future, we should allow an admin with E10/20 to specify a group that can modify subscriptions.
