### ISSUE TITLE
Allow user to delete a subscription via slash command

### ISSUE THREAD

**Issue by DHaussermann** [mattermost/mattermost-plugin-confluence#48]
Currently there is no way to Delete or deactivate a subscription once you've created it in the channel. 

Since this functionality does not exist, and space/page IDs can't be edited the only way to stop the events is to remove all events from the existing subscription. 

We should be able to delete subscriptions via a slash command.

**Comment by DHaussermann** [comment]
Disregard this issue. I forgot about the unsubscribe.

**Comment by aaronrothschild** [comment]
@DHaussermann Had me worried for a sec... ;)

**Comment by DHaussermann** [comment]
@aaronrothschild same! I was baffled. I knew there was a way to remove them during the first round of testing but I couldn't see it anymore :)
