### ISSUE TITLE
Create version bump and market place PRs for Confluence 

### ISSUE THREAD

**Issue by DHaussermann** [mattermost/mattermost-plugin-confluence#51]
All PRs required for the 1st release of confluence have now been merged. We need a version bump PR for Confluence as well as a corresponding Market Place PR.

@aaronrothschild the last release was `v1.1.0`  So I'm assuming we're going with `v1.2.0`

**Comment by aaronrothschild** [comment]
Thanks @DHaussermann Yes, let's go with 1.2.0

**Comment by hanzei** [comment]
I can take care of submitting it to the Marketplace.
