### ISSUE TITLE
make apply produces invalid files

### ISSUE THREAD

**Issue by hanzei** [mattermost/mattermost-plugin-confluence#54]
`make apply` does output the files with escaped `\n` resulting in the output:
`// This file is automatically generated. Do not modify it manually.\n\npackage config\n\nconst (\n\tPluginName = "com.mattermost.confluence"\n)`

This should be fixed by synchronising the build tools with https://github.com/mattermost/mattermost-plugin-starter-template

**Comment by hanzei** [comment]
@jfrerich I'm wondering if you might take a look at this once you are done with the SET rotation

**Comment by jfrerich** [comment]
@hanzei, sure.  I've self-assigned the issue.
