### ISSUE TITLE
Add autocomplete icon

### ISSUE THREAD

**Issue by hanzei** [mattermost/mattermost-plugin-confluence#72]
Since v5.24 slash commands can provide an `svg` via  `AutocompleteIconData` in `model.Command` that is then shown in the autocomplete list. This ticket is about adding the icon in `assets` to the slash command.

Include screenhots from a dark and a bright theme in the PR description, as there might be the need for a separate icon with a white background for autocomplete.

Similar PRs:
For GitHub plugin https://github.com/mattermost/mattermost-plugin-github/pull/359
For Jira plugin https://github.com/mattermost/mattermost-plugin-jira/pull/653

**Comment by goldsziggy** [comment]
I'd like to take this

**Comment by hanzei** [comment]
Awesome, thanks @goldsziggy Let me know if you have any questions.

**Comment by goldsziggy** [comment]
@hanzei I threw my attempt up for this one.  I couldn't exactly follow the same edits as the two other mentioned plugins as this one is structured slightly different.

Let me know if that works!!

**Comment by hanzei** [comment]
That looks quite good :+1: Nice use of an Interface
